### ISSUE TITLE
failed to open stream: No such file or directory ... autoload.php on line 17

### ISSUE THREAD

**Issue by connor11528** [ammezie/support-ticket#1]
I am getting an error when I try to fire up this project!

```
$ php artisan migrate

Warning: require(/Users/connorleech/Projects/support-ticket-full/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/connorleech/Projects/support-ticket-full/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Users/connorleech/Projects/support-ticket-full/bootstrap/../vendor/autoload.php' (include_path='.:') in /Users/connorleech/Projects/support-ticket-full/bootstrap/autoload.php on line 17
```

**Comment by ammezie** [comment]
You need to do `composer install` after cloning the project.

**Comment by connor11528** [comment]
Okay got it! I keep running in to this one. I think it is unrelated. I do `composer install` and run in to this:

![screen shot 2016-08-22 at 8 51 32 pm](https://cloud.githubusercontent.com/assets/3578908/17879912/5de94820-68aa-11e6-8e99-fce2b4d249f6.png)

I think it is because I have not set up a database properly or done it on my machine. I am running Mac OSX. Have you ever encountered this? Do you know how to resolve it?

Thank you. Full log:

```
support-ticket-full git:(master) php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes



  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory  


➜  support-ticket-full git:(master) sublime .
➜  support-ticket-full git:(master) touch .env
➜  support-ticket-full git:(master) php artisan migrate


  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused  
```

I am new to laravel so help getting set up or resources would be much appreciated! Not sure what I am doing wrong here

**Comment by connor11528** [comment]
Pasted in from `.env.example` Maybe I need to create new SQL database or does Laravel do it for us?

**Comment by ammezie** [comment]
Are you using homestead? You need to create a database and enter the correct database details (database name, username, password) in your `.env` file.

**Note:** in case you don't already have a `.env` file, rename `.env.example` to `.env`
