### ISSUE TITLE
[Enhancement] It should be more like a package.

### ISSUE THREAD

**Issue by Modelizer** [ammezie/support-ticket#2]
Hi,
   I have current Laravel instance and wants to try in my app.

Thanks.

**Comment by ammezie** [comment]
Will look into that.

**Comment by Modelizer** [comment]
Do it has similar concept like [thekordy](https://github.com/thekordy/ticketit) package? Or you have something new?

**Comment by yordadev** [comment]
Nothing special here, take a peak at the controllers on how to implement into your app @Modelizer. 
**Good work** @ammezie -- Couldn't find anything to make a pull request for, bord and looking to contribute to laravel projects!

**Comment by ammezie** [comment]
Thanks @Devitgg for the kind words. Mind looking at [openlaravel](https://github.com/ammezie/openlaravel)?

**Comment by yordadev** [comment]
@ammezie at quick glance at it, it looks well constructed -- very clean. There are a few instances where you don't keep a standardize `->with()` layout; mostly just for presentation and your API Routing should go into `routes/api.php`.

Other than that at a quick glance, I didn't look into the resource folder btw -- very well constructed. I like the idea of it. 

I'll make a pull request and fix the issues pointed out.
