### ISSUE TITLE
database config file

### ISSUE THREAD

**Issue by jespersgaard** [ammezie/support-ticket#3]
Hello

what settings do i put in here:
$url = parse_url(getenv("CLEARDB_DATABASE_URL"));
$server   = $url["host"];
$username = $url["user"];
$password = $url["pass"];
$database = substr($url["path"], 1);

it gives me an error?

rgds Martin

**Comment by ammezie** [comment]
Those are cleardb database details to be used if hosting with Heroku.

**Comment by jespersgaard** [comment]
so I can just delete them or?

**Comment by ammezie** [comment]
Yeah you can delete them and use your database details from the `.env` file.

**Comment by RichardJMora** [comment]
Remove 
$url = parse_url(getenv("CLEARDB_DATABASE_URL"));
$server   = $url["host"];
$username = $url["user"];
$password = $url["pass"];
$database = substr($url["path"], 1);

And the variables ,$server  ,$database  ,$username  ,$password

'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', $server),
            // 'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', $database),
            'username' => env('DB_USERNAME', $username),
            'password' => env('DB_PASSWORD', $password),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
